install:
  - choco install gitversion.portable -pre -y

assembly_info:
  patch: false

image: Visual Studio 2017

before_build:
- ps: dotnet restore src\zubenet.common.sln
- ps: gitversion /l console /output buildserver

environment:
  nuget_api_key:
    secure: l3HSwlDVK+wEMmgNl9qg8wBnwHs1Wr5n1AQohpuIq438BWicV0Coqvt4OQbjgkTs
  myget_api_key:
    secure: j/Q3Ej+QBPe9ly0F18AMMmva0PM5rDtypFWl4h8u92QrZyOVzwaVz7ScMZFb5a/r

build_script:
  - ps: .\build.ps1

artifacts:
- path: .\artifacts\*.nupkg

# after_build:
#   - cmd: ECHO nuget pack <Project>\<NuSpec>.nuspec -version "%GitVersion_NuGetVersion%" -prop "target=%CONFIGURATION%"
#   - cmd: nuget pack <Project>\<NuSpec>.nuspec -version "%GitVersion_NuGetVersion%" -prop "target=%CONFIGURATION%"
#   - cmd: appveyor PushArtifact "<NuSpec>.%GitVersion_NuGetVersion%.nupkg"